In [41]:
"""
หาผลรวมจากแกน axis
tf.math.reduce_sum(
    input_tensor, axis=None, keepdims=False, name=None
)
"""

'\nหาผลรวมจากแกน axis\ntf.math.reduce_sum(\n    input_tensor, axis=None, keepdims=False, name=None\n)\n'

In [42]:
import tensorflow as tf

In [43]:
# x has a shape of (2, 3) (two rows and three columns):
x = tf.constant([[1, 1, 1], [1, 1, 1]])
x.numpy()
""""
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)
"""
# sum all the elements
# 1 + 1 + 1 + 1 + 1+ 1 = 6
tf.reduce_sum(x).numpy()


6

In [44]:
# reduce along the first dimension
# the result is [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
print(x)
tf.reduce_sum(x, 0).numpy()
# array([2, 2, 2], dtype=int32)


tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


array([2, 2, 2])

In [45]:
# reduce along the second dimension
# the result is [1, 1] + [1, 1] + [1, 1] = [3, 3]
print(x)
tf.reduce_sum(x, 1).numpy()


tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


array([3, 3])

In [46]:
# keep the original dimensions
print(x)
tf.reduce_sum(x, 1, keepdims=True).numpy()



tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


array([[3],
       [3]])

In [47]:
# reduce along both dimensions
# the result is 1 + 1 + 1 + 1 + 1 + 1 = 6
# or, equivalently, reduce along rows, then reduce the resultant array
# [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
# 2 + 2 + 2 = 6
print(x)
tf.reduce_sum(x, [0, 1]).numpy()


tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


6

In [48]:
y = tf.constant([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
    ])
y.numpy()

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
# เอาทุกแถวมารวมกัน คงคอลั่มไว้
tf.reduce_sum(y, 0).numpy()

array([3, 3, 3, 3])

In [50]:
# เอาทุกคอลั่มมาบวกกัน คงแถวไว้
tf.reduce_sum(y, 1).numpy()

array([4, 4, 4])

In [51]:
tf.reduce_sum(y, [0, 1]).numpy()

12

In [52]:
z = tf.constant(
    [
        [
            [1, 2, 3, 1], [2, 1, 3, 4], [3, 5, 1, 1]
        ],
        [
            [1, 2, 3, 4], [2, 1, 5, 4], [3, 1, 1, 1]
        ]
    ]
)
z.shape

TensorShape([2, 3, 4])

In [62]:
# ทำ axis ไหน จะหายไป โดยจะเหลือ axis อื่นไว้
print(tf.reduce_sum(z, axis=0).numpy().shape)
print(tf.reduce_sum(z, axis=0).numpy())

(3, 4)
[[2 4 6 5]
 [4 2 8 8]
 [6 6 2 2]]


In [65]:
print(tf.reduce_sum(z, axis=1).numpy().shape)
print(tf.reduce_sum(z, axis=1).numpy())

(2, 4)
[[6 8 7 6]
 [6 4 9 9]]


In [60]:
print(tf.reduce_sum(z, axis=2).numpy().shape)
print(tf.reduce_sum(z, axis=2).numpy())

(2, 3)
[[ 7 10 10]
 [10 12  6]]


In [63]:
z = tf.constant(
    [
        [
            [1, 2, 3, 1], [2, 1, 3, 4], [3, 5, 1, 1]
        ],
        [
            [1, 2, 3, 4], [2, 1, 5, 4], [3, 1, 1, 1]
        ]
    ]
)
z.shape

TensorShape([2, 3, 4])

In [64]:
# ทำทีละช่องเริ่มจาก axis 0 ก่อน
# แล้วค่อยทำ axis 1 ซึ่งจะมองเป็น axis 0
print(tf.reduce_sum(z, axis=[0, 1]).numpy().shape)
print(tf.reduce_sum(z, axis=[0, 1]).numpy())

(4,)
[12 12 16 15]
